# Generated by Django 6.0.3 on 2026-04-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='zip',
        ),
    ]
