# Generated by Django 6.0.3 on 2026-04-05 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0002_remove_contact_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 5, 22, 26, 5, 417674)),
        ),
        migrations.AddField(
            model_name='contact',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
