# Generated by Django 6.0.3 on 2026-04-09 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0003_contact_date_contact_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aamount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 9, 19, 29, 23, 943564)),
        ),
    ]
