# Generated by Django 6.0.3 on 2026-04-09 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0004_aamount_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 9, 19, 34, 48, 989562)),
        ),
    ]
