# Generated by Django 6.0.3 on 2026-04-10 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0005_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aamount',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 10, 15, 24, 38, 639122)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 10, 15, 24, 38, 599142)),
        ),
    ]
