# Generated by Django 6.0.3 on 2026-04-11 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0006_aamount_date_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aamount',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aamount',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 11, 9, 47, 2, 633851)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 11, 9, 47, 2, 590843)),
        ),
    ]
