# Generated by Django 6.0.3 on 2026-04-11 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0007_aamount_category_alter_aamount_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aamount',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 11, 10, 0, 30, 357718)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 11, 10, 0, 30, 318719)),
        ),
    ]
