# Generated by Django 6.0.3 on 2026-04-11 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0008_alter_aamount_date_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aamount',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='aamount',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 11, 10, 9, 13, 560338)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 11, 10, 9, 13, 522331)),
        ),
    ]
