# Generated by Django 6.0.3 on 2026-04-11 15:54

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0009_alter_aamount_category_alter_aamount_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aamount',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(db_default=datetime.datetime(2026, 4, 11, 21, 24, 2, 352568)),
        ),
    ]
