# Generated by Django 6.0.3 on 2026-04-11 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0011_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aamount',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
