# Generated by Django 6.0.3 on 2026-04-27 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0015_aamount_user_aincome_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADDGOALS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalname', models.CharField(max_length=11)),
                ('goaltype', models.CharField(max_length=11)),
                ('targetamount', models.FloatField(default=0)),
                ('targetdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('currentsaving', models.FloatField(default=0)),
                ('prioritystatus', models.CharField(max_length=11)),
                ('aistatus', models.CharField(max_length=11)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
