# Generated by Django 6.0.3 on 2026-05-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0016_addgoals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addgoals',
            name='aistatus',
            field=models.CharField(default='off', max_length=11),
        ),
        migrations.AlterField(
            model_name='addgoals',
            name='goalname',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='addgoals',
            name='goaltype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addgoals',
            name='prioritystatus',
            field=models.CharField(default='off', max_length=11),
        ),
    ]
