# Generated by Django 6.0.3 on 2026-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0018_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='aincome',
            name='category',
            field=models.CharField(default='Other', max_length=200),
        ),
    ]
