# Generated by Django 6.0.3 on 2026-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0019_aincome_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aincome',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
