# Generated by Django 6.0.3 on 2026-05-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0020_alter_aincome_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addgoals',
            name='prioritystatus',
            field=models.CharField(blank=True, default='off', max_length=11),
        ),
    ]
