# Generated by Django 6.0.3 on 2026-06-03 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0022_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
