# Generated by Django 6.0.3 on 2026-06-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FP', '0023_passwordresetotp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addgoals',
            name='goalid',
            field=models.CharField(default=1234567, max_length=7),
            preserve_default=False,
        ),
    ]
